stages:
  - build-stage
  - deploy-stage

build-job:
  stage: build-stage
  tags:
    - shell
  script:
    - git clone https://github.com/cicd-hackathon-stgt/spring-boot-sample-app.git
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_ID}"
    when: always
    expire_in: 7d
    paths:
      - "*"

deploy-job:
  stage: deploy-stage
  tags:
    - shell
  script:
    - cd spring-boot-sample-app
    - ./mvnw install -D skipTests
    - "cf login -a ${CF_API} -u ${CF_USER} -p \"${CF_PASS}\""
    - cf push sample-app -p target/spring-boot-sample-app-0.0.1-SNAPSHOT.jar --random-route
    
