stages:
  - build-stage
  - deploy-stage
  - test-stage

build-job:
  stage: build-stage
  environment:
    - name: dev
    - url: http://sample-app-chatty-duiker.cfapps.io/
  tags:
    - shell
  script:
    - ./mvnw install -D skipTests
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_ID}"
    when: always
    expire_in: 7d
    paths:
      - "target/spring-boot-sample-app-*-SNAPSHOT.jar"

deploy-job:
  stage: deploy-stage
  tags:
    - shell
  environment: dev
  script:
    - "cf login -a ${CF_API} -u ${CF_USER} -p \"${CF_PASS}\""
    - cf push sample-app -p target/spring-boot-sample-app-*-SNAPSHOT.jar --hostname sample-app

test-job:
  stage: test-stage
  tags:
    - shell
  script:
    - curl --silent http://sample-app-chatty-duiker.cfapps.io/actuator/health | jq '.status' | grep -o UP
